# Generated by Django 5.0.2 on 2024-02-11 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="New_bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_name",
                    models.CharField(max_length=20, verbose_name=" Называние"),
                ),
                ("title_text", models.TextField(verbose_name="Описание")),
                (
                    "photo",
                    models.URLField(blank=True, null=True, verbose_name="Фотография"),
                ),
            ],
            options={
                "verbose_name": "Курорт",
                "verbose_name_plural": "Курорттар",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                ("booking_date", models.DateField(verbose_name="Дата бронирования")),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tours.new_bookings",
                        verbose_name="Курорт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
    ]
